### ISSUE TITLE
src/LabeledTextInput.lua "parent" not declared

### ISSUE THREAD

**Issue by FieryEvent** [Roblox/StudioWidgets#1]
No value was assigned to `parent`:
@ line 27
![image](https://user-images.githubusercontent.com/34844696/39020637-015abe5e-4404-11e8-89dc-72ed811a7632.png)
https://github.com/Roblox/StudioWidgets/blob/master/src/LabeledTextInput.lua#L27

**Comment by LPGhatguy** [comment]
I'll help set up a commit check for the project at some point in the future to use Luacheck to catch things like this before they're submitted.
