### ISSUE TITLE
CustomTextButton's methods do not follow the coding style

### ISSUE THREAD

**Issue by LucasWolschick** [Roblox/StudioWidgets#13]
`function CustomTextButtonClass:getButton()` should be `function CustomTextButtonClass:GetButton()` as according to https://github.com/Roblox/StudioWidgets#coding-conventions.

**Comment by dougbankspersonal** [comment]
True.  If you want to make the update I will approve.

**Comment by cliffchapmanrbx** [comment]
Hi there, thank you for your feedback. We're archiving this repository as we move in a new direction with UI frameworks in Roblox. You're welcome to fork this repository to resolve the bug yourself, however we do not have the resources to maintain this repository while improving core functionality of the Roblox client UI.
