### ISSUE TITLE
LabeledMultiChoice.new won't work properly

### ISSUE THREAD

**Issue by swordlink1** [Roblox/StudioWidgets#17]
I'm trying to get something to work so I can copy the the LabeledMultiChoice from the PluginGuiService, unfortunately, I have no luck. If I try a local plugin in my plugins folder, it prints out `16:40:56.495 - forrobloxosthingy.lua:19: attempt to index nil with 'new'` and as a installed published plugin prints out `16:55:02.143 - Plugin_4087104785.Script:19: attempt to index nil with 'new'`. If that happens, then it is likely that saving a local plugin not in my plugins folder or `pcall(function()` won't work too. If you want to download the code, click [here.](https://github.com/Roblox/StudioWidgets/files/3709393/Plugin.File.zip)

Thanks.
Plus judging by the `attempt to index nil with 'new'`, it might have been removed.

**Comment by Alts-Alt** [comment]
It doesn't look like you have added the project to your file structure.

Use the following in the cmd line to add the StudioWidgets project folder to your workspace. This can then be placed anywhere and also saved with your plugin.
```lua
local http = game:GetService("HttpService")
local req = http:GetAsync("https://api.github.com/repos/Roblox/StudioWidgets/contents/src")
local json = http:JSONDecode(req)

local targetFolder = Instance.new("Folder")
targetFolder.Name = "StudioWidgets"
targetFolder.Parent = game.Workspace

for i = 1, #json do
	local file = json[i]
	if (file.type == "file") then
		local name = file.name:sub(1, #file.name-4)
		local module = targetFolder:FindFirstChild(name) or Instance.new("ModuleScript")
		module.Name = name
		module.Source = http:GetAsync(file.download_url)
		module.Parent = targetFolder
	end
end
```

You will also need to Require() the LabeledMultiChoice module inside the StudioWidgets to be able to use the LabeledMultiChoice.new() function.

**Comment by swordlink1** [comment]
Thank you! 😊 I did had to turn on HTTPService, which I forgot.
