### ISSUE TITLE
src/LabeledTextInput.lua Full-width Textbox

### ISSUE THREAD

**Issue by Wesleyyy** [Roblox/StudioWidgets#2]
With all widgets aiming to replicate the Properties panel, I found the default behavior of LabeledTextInput to be breaking the full-width consistency. I think all developers will benefit from the following change.

Current:
https://github.com/Roblox/StudioWidgets/blob/fa75191f92eeed3deb6ef0347f4112726f2f37a3/src/LabeledTextInput.lua#L40 Proposed:
`textBoxWrapperFrame.Size = UDim2.new(1,-(GuiUtilities.StandardLineElementLeftMargin+GuiUtilities.StandardLineLabelLeftMargin), 0.6, 0)`

Visual result:
![image](https://user-images.githubusercontent.com/7376347/39029025-a36fc19e-440e-11e8-9e6c-6e2462ca0ded.png)

As this removes the kTextInputWidth variable from the equation, line 10 would become obsolete:
https://github.com/Roblox/StudioWidgets/blob/fa75191f92eeed3deb6ef0347f4112726f2f37a3/src/LabeledTextInput.lua#L10

**Comment by dougbankspersonal** [comment]
Let me talk to our UX people about this.  Stay tuned.

**Comment by dougbankspersonal** [comment]
This library was developed to support to new Terrain Tools (in a lua widget).
The UX people here have decided they like the Random Seed box (a text input box) like it is, fixed width.
I agree that for general purposes flexible width would be nice.
I will try to get to it, but honestly it will be fairly back burner.  If someone out there wants to submit a CL adding a "stretch to fit" option to the TextInput widget, I will happily review & merge the CL.

**Comment by cliffchapmanrbx** [comment]
Hi there, thank you for your feedback. We're archiving this repository as we move in a new direction with UI frameworks in Roblox. You're welcome to fork this repository to resolve the bug yourself, however we do not have the resources to maintain this repository while improving core functionality of the Roblox client UI.
