### ISSUE TITLE
src/labeledcheckbox.lua error when using LabeledMultiChoice.new()

### ISSUE THREAD

**Issue by ghost** [Roblox/StudioWidgets#6]
When using the code: `LabeledMultiChoice.new("LabeledMultiChoice", "LabeledMultiChoice", {'Labeled', 'Multi', 'Choice'}, 1)` I get the error `Workspace.SubWidgets.Modules.StudioWidgets.LabeledCheckbox:46: attempt to concatenate local 'nameSuffix' (a nil value)`. The labelled multi choice does not appear.

Here's the full output:

```
17:41:23.428 - Workspace.SubWidgets.Modules.StudioWidgets.LabeledCheckbox:46: attempt to concatenate local 'nameSuffix' (a nil value)
17:41:23.428 - Stack Begin
17:41:23.428 - Script 'Workspace.SubWidgets.Modules.StudioWidgets.LabeledCheckbox', Line 46 - field new
17:41:23.429 - Script 'Workspace.SubWidgets.Modules.StudioWidgets.LabeledRadioButton', Line 22 - field new
17:41:23.429 - Script 'Workspace.SubWidgets.Modules.StudioWidgets.LabeledMultiChoice', Line 112 - method _AddRadioButton
17:41:23.430 - Script 'Workspace.SubWidgets.Modules.StudioWidgets.LabeledMultiChoice', Line 102 - method _MakeRadioButtons
```

**Comment by dougbankspersonal** [comment]
@Sublivion 
This is not a bug.
The "choices" array is an array of entries.
Each entry has two fields: 
Id - a unique text string identifying the choice.  Not user-facing.
Text - a user-facing label for the choice.

I will update the code to include a comment to this effect.
